// export { default as AppService } from './app.service';
export { default as AuthService } from './auth.service';
export { default as AllService } from './all.service';
// export { default as MainService } from './main.service';
// export { default as NewsService } from './news.service';
// export { default as CareerService } from './career.service';
// export { default as DirectionService } from './direction.service';
// export { default as AboutService } from './about.service';
// export { default as ContactsService } from './contacts.service';
// export { default as FeedbackService } from './feedback.service';
