export { default as AuthService } from './auth.service';
export { default as AllService } from './all.service';
export { default as AlbumService } from './album.service';
export { default as SongService } from './song.service';
export { default as UserService } from './user.service';
export { default as PromotionService } from './promotion.service';
export { default as CooperationService } from './cooperation.service';
export { default as ChatService } from './chat.service';
export { default as MainService } from './main.service';
